route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    webhook_configs:
        - url: 'https://webhook.site/b160ffdc-050d-4091-92d6-97947562852a'
